# Generated by Django 2.2 on 2020-05-25 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('data_request', models.DateTimeField(auto_now_add=True)),
                ('data_accept', models.DateTimeField(blank=True, null=True)),
                ('delay', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('adopted', 'adopted'), ('processing', 'processing'), ('completed', 'completed')], default='adopted', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.DurationField()),
                ('temperature', models.SmallIntegerField()),
                ('illumination', models.SmallIntegerField()),
                ('microrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microrequest', to='data_viewer.Microrequest')),
            ],
        ),
    ]
